{{- if not .Values.secretEnv.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "velora.fullname" . }}
  labels:
    {{- include "velora.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  VELORA_DATABASE_DSN: {{ .Values.secretEnv.databaseDSN | quote }}
  VELORA_DATABASE_READONLY_DSN: {{ .Values.secretEnv.databaseReadOnlyDSN | quote }}
  VELORA_CRYPTO_KEY: {{ .Values.secretEnv.cryptoKey | quote }}
  VELORA_REDIS_USERNAME: {{ .Values.secretEnv.redisUsername | quote }}
  VELORA_REDIS_PASSWORD: {{ .Values.secretEnv.redisPassword | quote }}
  VELORA_KAFKA_USERNAME: {{ .Values.secretEnv.kafkaUsername | quote }}
  VELORA_KAFKA_PASSWORD: {{ .Values.secretEnv.kafkaPassword | quote }}
  VELORA_SEARCH_USERNAME: {{ .Values.secretEnv.searchUsername | quote }}
  VELORA_SEARCH_PASSWORD: {{ .Values.secretEnv.searchPassword | quote }}
  VELORA_STORAGE_ACCESS_KEY: {{ .Values.secretEnv.storageAccessKey | quote }}
  VELORA_STORAGE_SECRET_KEY: {{ .Values.secretEnv.storageSecretKey | quote }}
  VELORA_NACOS_USERNAME: {{ .Values.secretEnv.nacosUsername | quote }}
  VELORA_NACOS_PASSWORD: {{ .Values.secretEnv.nacosPassword | quote }}
  VELORA_ROCKETMQ_ACCESS_KEY: {{ .Values.secretEnv.rocketmqAccessKey | quote }}
  VELORA_ROCKETMQ_SECRET_KEY: {{ .Values.secretEnv.rocketmqSecretKey | quote }}
  VELORA_BOOTSTRAP_ADMIN: {{ .Values.secretEnv.bootstrapAdmin | quote }}
  VELORA_BOOTSTRAP_PASSWORD: {{ .Values.secretEnv.bootstrapPassword | quote }}
  VELORA_OIDC_CLIENT_SECRET: {{ .Values.secretEnv.oidcClientSecret | quote }}
{{- end }}
