ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG VELORA_VERSION=dev
ARG VELORA_REVISION=unknown
ARG VELORA_BUILD_DATE=unknown
LABEL org.opencontainers.image.title="Velora Server" \
      org.opencontainers.image.version="${VELORA_VERSION}" \
      org.opencontainers.image.revision="${VELORA_REVISION}" \
      org.opencontainers.image.created="${VELORA_BUILD_DATE}" \
      org.opencontainers.image.source="https://github.com/sevoniva-labs/velora"
COPY --chown=10001:10001 velora /usr/local/bin/velora
COPY --chown=10001:10001 velora-worker /usr/local/bin/velora-worker
COPY --chown=10001:10001 velora-connect /usr/local/bin/velora-connect
COPY --chown=10001:10001 velora-migrate /usr/local/bin/velora-migrate
COPY --chown=10001:10001 velora-storage-check /usr/local/bin/velora-storage-check
