package kratosapi

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"
	"strings"

	"github.com/sevoniva-labs/velora/server/internal/platform/database"
)

const casdoorAuthorizeInternalPath = "/_velora/casdoor-authorize"

type authorizationApplication struct {
	Code         string
	Name         string
	RedirectURIs []string
}

// AuthorizationHandler is the public OIDC authorization gate. It keeps the
// identity provider UI private while preserving the standard authorization
// code + PKCE request generated by a downstream application.
func (b *SessionBridge) AuthorizationHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("Pragma", "no-cache")
		if r.Method != http.MethodGet || !b.allowedHost(r.Host) {
			http.Error(w, "not found", http.StatusNotFound)
			return
		}

		app, ok := b.authorizedApplication(r)
		if !ok {
			http.Error(w, "invalid authorization request", http.StatusBadRequest)
			return
		}
		if !b.hasGatewaySession(r) {
			b.clearGatewayCookie(w)
			http.Redirect(w, r, b.portalLoginURL(app, r.URL.RawQuery), http.StatusFound)
			return
		}

		// Nginx consumes this header and proxies internally to Casdoor. The
		// browser keeps the public standards-compliant authorization URL, while
		// Casdoor itself is never selected as the interactive login surface.
		target := casdoorAuthorizeInternalPath
		if r.URL.RawQuery != "" {
			target += "?" + r.URL.RawQuery
		}
		w.Header().Set("X-Accel-Redirect", target)
		w.WriteHeader(http.StatusOK)
	})
}

func (b *SessionBridge) GatewayLogoutHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		if r.Method != http.MethodPost || !b.allowedHost(r.Host) {
			http.Error(w, "not found", http.StatusNotFound)
			return
		}
		if cookie, err := r.Cookie(gatewaySessionCookie); err == nil && len(cookie.Value) <= maxBridgeTicket {
			_ = b.cache.Delete(r.Context(), gatewaySessionKey(cookie.Value))
		}
		b.clearGatewayCookie(w)
		w.WriteHeader(http.StatusNoContent)
	})
}

func (b *SessionBridge) authorizedApplication(r *http.Request) (authorizationApplication, bool) {
	query := r.URL.Query()
	clientID := strings.TrimSpace(query.Get("client_id"))
	redirectURI := strings.TrimSpace(query.Get("redirect_uri"))
	state := strings.TrimSpace(query.Get("state"))
	challenge := strings.TrimSpace(query.Get("code_challenge"))
	if clientID == "" || len(clientID) > 255 || redirectURI == "" || len(redirectURI) > 2048 || state == "" || len(state) > 512 ||
		challenge == "" || len(challenge) > 256 || query.Get("response_type") != "code" || query.Get("code_challenge_method") != "S256" {
		return authorizationApplication{}, false
	}
	redirect, err := url.Parse(redirectURI)
	if err != nil || redirect.Scheme != "https" || redirect.Host == "" || redirect.User != nil || redirect.Fragment != "" {
		return authorizationApplication{}, false
	}

	app, err := b.resolveApplication(r.Context(), clientID)
	if err != nil {
		return authorizationApplication{}, false
	}
	for _, allowed := range app.RedirectURIs {
		if strings.TrimSpace(allowed) == redirectURI {
			return app, true
		}
	}
	return authorizationApplication{}, false
}

func resolveAuthorizationApplication(db *database.DB) func(context.Context, string) (authorizationApplication, error) {
	return func(ctx context.Context, clientID string) (authorizationApplication, error) {
		if db == nil {
			return authorizationApplication{}, errors.New("authorization application database is unavailable")
		}
		var app authorizationApplication
		var redirectJSON string
		err := db.QueryRowContext(ctx, db.Rebind(`SELECT a.code,a.name,b.redirect_uris_json
		FROM portal_applications a
		JOIN portal_application_identity_bindings b ON b.application_id=a.id AND b.organization_id=a.organization_id
		WHERE b.public_client_id=? AND b.provider_key='casdoor' AND b.protocol='OIDC'
		  AND b.configuration_status='CONFIGURED' AND b.verification_status='PASSED'
		  AND a.status='ENABLED' AND a.lifecycle_status='PUBLISHED'
		LIMIT 1`), clientID).Scan(&app.Code, &app.Name, &redirectJSON)
		if err != nil {
			return authorizationApplication{}, err
		}
		if err := json.Unmarshal([]byte(redirectJSON), &app.RedirectURIs); err != nil {
			return authorizationApplication{}, err
		}
		return app, nil
	}
}

func (b *SessionBridge) hasGatewaySession(r *http.Request) bool {
	cookie, err := r.Cookie(gatewaySessionCookie)
	if err != nil || strings.TrimSpace(cookie.Value) == "" || len(cookie.Value) > maxBridgeTicket {
		return false
	}
	value, err := b.cache.Get(r.Context(), gatewaySessionKey(cookie.Value))
	return err == nil && value == "active"
}

func (b *SessionBridge) portalLoginURL(app authorizationApplication, rawQuery string) string {
	target := *b.portalURL
	target.Path = "/login"
	target.RawPath = ""
	query := url.Values{}
	query.Set("app", app.Code)
	query.Set("app_name", app.Name)
	continuation := "/login/oauth/authorize"
	if rawQuery != "" {
		continuation += "?" + rawQuery
	}
	query.Set("redirect", continuation)
	target.RawQuery = query.Encode()
	target.Fragment = ""
	return target.String()
}

func (b *SessionBridge) clearGatewayCookie(w http.ResponseWriter) {
	http.SetCookie(w, &http.Cookie{Name: gatewaySessionCookie, Value: "", Path: "/", HttpOnly: true, Secure: b.secure, SameSite: b.sameSite, MaxAge: -1})
}
